# -*- coding: utf-8 -*-
# Spring Boot 应用配置
spring:
  application:
    name: fraud-detection-system   # 应用名称，用于标识服务
  profiles:
    active: default                # 激活的配置环境（默认 default）

# Google Cloud Platform (GCP) 配置
gcp:
  project-id: spheric-engine-448906-m3          # GCP 项目 ID
  pubsub:
    topic-id: FraudDetection                   # Pub/Sub 主题 ID# 用于交易处理的主题
    subscription-id: FraudDetection-sub        # Pub/Sub 订阅 ID
    alert-topic-id: FraudAlerts         # 用于欺诈通知的主题
    # Base64 编码的 GCP 服务账号密钥
  service-account-key-base64: "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAic3BoZXJpYy1lbmdpbmUtNDQ4OTA2LW0zIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiM2FhNzg0OWM5Nzg4ZjU2MGRlMjM4MmVhNTVlZGZmNDY5ZjEwNzI4OSIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZRSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2N3Z2dTakFnRUFBb0lCQVFDNWNBZGNvNVBDeCtRRVxuMDZFazNVL3JZYVNHM2NGeWJQN3NKL2hVSElsM2F0Slp2ZGlrZXNGWS9WTHc2SExQQVVVOXNtMjFyV0J0RFBYUFxuL0dEWktmeHJUQ0RMaXA0ZGFsTkdDanhTc2NWZ0tnbnR5VnNoR0NUZUFnYXdWUEMxOU5zYmRVREllZnFwSVBTY1xuNGw0RUl1VVlldHc4Y1VFVnVubWNNMy8vdmRCcUFFZjZuQmxNNHBpc243YlV4QjNac3F5SDZEd2dyNlpLSzN4Q1xuWEE0YTVqQkpaclZ1NDJ4VmR2WDJ4VG9Bd1VvbCtQdDhTRTJZTHpCWEZ4ZzJKNXRiVW5BWWhqUXM5ZlNLOC9LbVxuRGgvaGFBeUxjSngzQ0lZYVZReWFGZVdWQVNCcWkvVlFrbXFOQWhzVHF2aXBoQ3V1YzI5MnE4a0pTUHFRbmNoelxuTGxuNFJTNDFBZ01CQUFFQ2dnRUFHK25DSWU2NWlrTmVqbDl3elVUSEIrNXR2cU5Zd0NtcUFkQk9jQkxQbW5zb1xuNkx0TUJnNDRWblhqYTBJQ0xpakp6R3kwV1BtZEh5MHBQMEtGTFl0RlpMMVQzbStpTjFsTzZhY1d4M2ZjOXdtOFxuN3Q4MWFYamg2ODB3UnBDeW55RVpianVySWNKQ3VmeXM5WVNabEZQUVdtdjhCTmtqYStyaTdXRlBMaWJiWFdrbFxuam55SWl2ZWFhY2VLdEJtOTlnZmZoS3krMndvTDBCMEc2Y3R0NWxNVlloSkV2MlNLY0oyWDJZaGxtbmIwK085TVxueDVJeUp3YVprR3pXTThoeEczcWt6eFpUcFk1OHRwVkd0Mit2WWs1ZHFQKzBjNjdqRGVObHFZZHJXSTQrc3A1UlxudnpEMytDWWM2SWd3SnUzM3BsRWlYRmN0R3RXWlpqUEMwUThUaTlLbVlRS0JnUUR1c2kwZk9JZUFDeS82ZVZyNVxuN3Z6ajNPS0lPZzFxdmNuaUpyTkdPdFV6a1FJclhyL0tmTkw5UkFQOHZOSE1ScXZsWmQweUhGVHVNdlFTYXpFQVxuL2xwMEVOdjhnVzFibXgrZU9BTCtxUk1lMUd4dWplZ0VkRHdaYlpIaWVxUnJyYUdzNVd4SnJQTUNRSzFralR5YVxuenFoZUgvUk5RdThIVWZXTy93VElSODQ1alFLQmdRREc0WFhUdGtHVHdVZFlNcldDc1g1eGllQjU2Rkt5M1NTUVxuN1I4WW81bysvay9ja1dQcVg1VFVrbmRhN2lFU1NQYTdJcEJUeWs2TmJDTjVOQ3pYamx2TzFObkQ3MEt1SXUwR1xuMklpQUh1R0hRT2dxei8rT2JCWTErTklNU2tCSXFJc3cvNE9zMlNkdjJFZ3JBakpGaUhNMVVjeFdCRTF2b1R6L1xuUngySjFEZ1pTUUtCZ0U1WXIxVExFamFsOVdhS1JLRTZuMGtQYkU5NGRvVHRySUVOWU5TUlpQOWEvbEpMOURtN1xuUk9tYVZKQzFUVXQyZXQ5OTB0K3F5dm13UWNwMTRvekg3OXFlMmdZRVdXZXkvK3JIeWJ2YXRRcnVnSFM5SVVXc1xuL1RqL2JOM2drVzFDZlltcGVDU3Fuc3pEZStaQU1YOUNpNkx4YkJlYis2YjBjTnd4dWxrZXNJTFZBb0dBSU1ZbVxuMUt6RVFjVW9MTEN1bU1zSE8wNnRYMm1adDBBYU5vZmRDQUp0K05PUDlabEFEZStTWnpWNzFkQklRdXNqUGRPRVxuVlVxUmgxeTZ1ODZOVlRod2lMVXE3YzhQL2dKamJTMWgwVHRGanpSekRoc1kwaStkdVdjM3RpN0dTVEw5UFNYZVxuWFMyc0FoSnlVaVFhaExybndYR3Bhc05xdjJxaTBxNjFmM0VwallFQ2dZRUF6d0pyV0ZveFQ5eE5sdnI1MHRXSVxuUkltdzVIMnJzMWZEQXd5YjNBM2dKV2xuVUNlb2llWlBlTHNGZ2FUUitzN2UxcWVsNXhYZjJqQThMVWp0T2FJSlxuc0xXL0lxdHV6SGxzSHFWTmhRcFp0akJWK3gxdnowbklCSXdpVXJHVG5hc3Fha3JhQ1JYcExjNzg0bW03ZWNZalxuVTBxN3YrWDBGT0NHN04xeEJaZnFoLzA9XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiZnJhdWRkZXRlY3Rpb25kZW1vQHNwaGVyaWMtZW5naW5lLTQ0ODkwNi1tMy5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMTAxMzk2MTc1OTQ0OTUzMDM2NTIiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2ZyYXVkZGV0ZWN0aW9uZGVtbyU0MHNwaGVyaWMtZW5naW5lLTQ0ODkwNi1tMy5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgInVuaXZlcnNlX2RvbWFpbiI6ICJnb29nbGVhcGlzLmNvbSIKfQo="

# 服务配置
server:
  port: 8080                                   # 服务运行的端口号

# 日志配置
logging:
  level:
    root: INFO                                 # 全局日志级别：INFO
    com.frauddetection: DEBUG                 # 指定包的日志级别：DEBUG
  file:
    name: logs/application.log                # 日志文件路径

# Google Pub/Sub 订阅者配置
pubsub:
  subscriber:
    maxAckExtensionPeriod: 60                 # 最大消息确认延长时间（秒）
    maxOutstandingElementCount: 1000          # 最大未确认的消息数量
    maxOutstandingRequestBytes: 10000000      # 最大未确认的消息字节数
mq:
  type: GCP


# 注意事项
# 1. 建议不要在配置文件中直接存储敏感信息（例如 service-account-key-base64）。可以通过环境变量注入，
#    使用 ${SERVICE_ACCOUNT_KEY} 引用密钥值。
# 2. 在生产环境中，建议将日志级别设置为 WARN 或 ERROR 以减少日志量。
# 3. 使用多环境配置时，创建 application-{profile}.yml 文件，按需覆盖默认配置。
# 4. 日志文件可以设置轮转策略（如最大大小和历史保留数量）。

