# -*- coding: utf-8 -*-
# Spring Boot 应用配置
spring:
  application:
    name: fraud-detection-system   # 应用名称，用于标识服务
  profiles:
    active: default                # 激活的配置环境（默认 default）

# Google Cloud Platform (GCP) 配置
gcp:
  project-id: spheric-engine-448906-m3          # GCP 项目 ID
  service-account-key-path:  ${GOOGLE_APPLICATION_CREDENTIALS}
  pubsub:
    topic-id: FraudDetection                   # Pub/Sub 主题 ID# 用于交易处理的主题
    subscription-id: FraudDetection-sub        # Pub/Sub 订阅 ID
    alert-topic-id: FraudAlerts         # 用于欺诈通知的主题

# 服务配置
server:
  port: 8080                                   # 服务运行的端口号

# 日志配置
logging:
  level:
    root: INFO                                 # 全局日志级别：INFO
    com.frauddetection: DEBUG                 # 指定包的日志级别：DEBUG
  file:
    name: logs/application.log                # 日志文件路径

# Google Pub/Sub 订阅者配置
pubsub:
  subscriber:
    maxAckExtensionPeriod: 60                 # 最大消息确认延长时间（秒）
    maxOutstandingElementCount: 1000          # 最大未确认的消息数量
    maxOutstandingRequestBytes: 10000000      # 最大未确认的消息字节数
mq:
  type: GCP

# 注意事项
# 1. 在生产环境中，建议将日志级别设置为 WARN 或 ERROR 以减少日志量。
# 2. 使用多环境配置时，创建 application-{profile}.yml 文件，按需覆盖默认配置。
# 3. 日志文件可以设置轮转策略（如最大大小和历史保留数量）。

