apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection
  labels:
    app: fraud-detection
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
    spec:
      containers:
        - name: fraud-detection
          image: northamerica-northeast1-docker.pkg.dev/spheric-engine-448906-m3/frauddetectiondemo/frauddetection:latest
          ports:
            - containerPort: 8080
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /app/credentials/service-account-key.json
          volumeMounts:
            - name: credentials-volume
              mountPath: /app/credentials/service-account-key.json
              subPath: service-account-key.json
            - name: config-volume
              mountPath: /app/config/application.yml
              subPath: application.yml
      volumes:
        - name: credentials-volume
          secret:
            secretName: google-credentials
        - name: config-volume
          configMap:
            name: fraud-detection-config
